<a href="#" class="box-banner">
	<img src="/assets/images/common/banner-footer.png" alt="" loading="lazy" class="full-image">
</a>
<a href="javascript:void(0)" class="page-top"><i class="fas fa-caret-up"></i></a>
<footer id="l-footer" class="l-footer">
	<div class="wrp-container">
		<ul class="l-footer__nav">
			<li class="l-footer__nav__item">
				<a href="★★★">Giới thiệu</a>
			</li>
			<li class="l-footer__nav__item">
				<a href="★★★">Liên hệ</a>
			</li>
			<li class="l-footer__nav__item">
				<a href="★★★">Thông tin quảng cáo</a>
			</li>
		</ul>
		<div class="l-footer__main">
			<div class="l-footer__main__info">
				<p class="l-footer__main__info__ttl">Cơ quan chủ quản: Công ty TNHH AAA</p>
				<p class="l-footer__main__info__txt">Trụ sở: Neque porro quisquam est, qui dolorem</p>
				<p class="l-footer__main__info__txt"><a href="tel:02812345678">Tel: (028) 1234 5678</a></p>
				<p class="l-footer__main__info__txt">Giấy phép: .......... ngày cấp....... <br>BỘ THÔNG TIN VÀ TRUYỀN THÔNG CỤC QL PHÁT THANH, TRUYỀN HÌNH VÀ THÔNG TIN ĐIỆN TỬ </p>
				<p class="l-footer__main__info__txt">Chịu trách nhiệm xuất bản: Tín chỉ Carbon</p>
			</div>
			<div class="l-footer__main__logo">
				<a href="/"><img src="/assets/images/common/logo.svg" alt="" class="fluid-image"></a>
			</div>
		</div>
	</div>
	<div class="l-footer__bottom">
		<div class="wrp-container">
			<small class="l-footer__bottom__copyright">&copy; Ghi rõ nguồn "Tín chỉ Carbon" khi phát hành lại thông tin từ website này</small>
		</div>
	</div>
</footer>